/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vending;

import java.util.List;

public class VendingMachineTest {
    
        public long selectItemAndGetPrice(Item item) {
            return 0;
        }
    
    public static void main(String[] args) {
    
    }

}
    

